export const products: ProductType[] = [
	{
		_id: "1",
		productName: "Timberlake Jacket",
		newPrice: 14500,
		oldPrice: 20000,
		media: [
			"/assets/products/product-3.png",
			"/assets/products/product-2.png",
			"/assets/products/product-5.jpg",
		],
		material: "aso-oke",
		categories: ["trendy", "men"],
		sizes: ["XS", "S", "M", "L"],
		colors: ["red", "blue", "green"],
		description:
			"A stylish jacket made from high-quality aso-oke fabric, perfect for any occasion.",
		createdAt: "2024-08-01",
		quantity: 10,
	},
	{
		_id: "2",
		productName: "Women's Dress",
		newPrice: 14500,
		oldPrice: 20000,
		media: [
			"/assets/products/product-1.jpg",
			"/assets/products/product-1.jpg",
			"/assets/products/product-1.jpg",
		],
		material: "ankara",
		categories: ["women", "trendy"],
		sizes: ["S", "M", "L"],
		colors: ["yellow", "purple", "black"],
		description:
			"An elegant dress made from vibrant ankara fabric, ideal for casual and formal events.",
		createdAt: "2024-08-15",
		quantity: 15,
	},
	{
		_id: "3",
		productName: "Men's Traditional Attire",
		newPrice: 18000,
		oldPrice: 22000,
		media: [
			"/assets/products/product-2.png",
			"/assets/products/product-2.png",
			"/assets/products/product-2.png",
		],
		material: "adire",
		categories: ["men", "trendy"],
		sizes: ["M", "L", "XL"],
		colors: ["blue", "white", "brown"],
		description:
			"Traditional attire crafted from rich adire fabric, perfect for cultural celebrations.",
		createdAt: "2024-07-20",
		quantity: 8,
	},
	{
		_id: "4",
		productName: "Children's Kaftan",
		newPrice: 7500,
		oldPrice: 10000,
		media: ["/assets/products/product-4.jpg", "/assets/products/product-4.jpg"],
		material: "ankara",
		categories: ["children", "trendy"],
		createdAt: "2024-05-10",
		sizes: ["XS", "S", "M"],
		colors: ["pink", "orange", "green"],
		description:
			"A colorful kaftan for children made from soft ankara fabric, great for everyday wear.",
		quantity: 20,
	},
	{
		_id: "5",
		productName: "Women's Maxi Dress",
		newPrice: 12000,
		oldPrice: 15000,
		media: ["/assets/products/product-5.jpg", "/assets/products/product-5.jpg"],
		material: "kente",
		categories: ["women", "trendy"],
		createdAt: "2024-06-25",
		sizes: ["M", "L", "XL"],
		colors: ["red", "blue", "gold"],
		description:
			"A stunning maxi dress made from luxurious kente fabric, perfect for summer outings.",
		quantity: 12,
	},
	{
		_id: "6",
		productName: "Men's Buba and Sokoto",
		newPrice: 16000,
		oldPrice: 20000,
		media: [
			"/assets/products/product-5.jpg",
			"/assets/products/product-5.jpg",
			"/assets/products/product-5.jpg",
		],
		material: "aso-oke",
		categories: ["men"],
		createdAt: "2024-07-01",
		sizes: ["M", "L", "XL"],
		colors: ["white", "black", "brown"],
		description:
			"A classic buba and sokoto set made from premium aso-oke fabric, suitable for formal events.",
		quantity: 5,
	},
	{
		_id: "7",
		productName: "Girls' Traditional Dress",
		newPrice: 8000,
		oldPrice: 10000,
		media: [
			"/assets/featuredProducts/featured-product-1.jpg",
			"/assets/featuredProducts/featured-product-1.jpg",
			"/assets/featuredProducts/featured-product-1.jpg",
		],
		material: "ankara",
		categories: ["men", "featured"],
		createdAt: "2024-08-05",
		sizes: ["S", "M"],
		colors: ["purple", "pink"],
		description:
			"A beautiful traditional dress for girls, made from colorful ankara fabric.",
		quantity: 25,
	},
	{
		_id: "8",
		productName: "Men's Agbada",
		newPrice: 25000,
		oldPrice: 30000,
		media: [
			"/assets/products/product-4.jpg",
			"/assets/products/product-4.jpg",
			"/assets/products/product-4.jpg",
		],
		material: "kente",
		categories: ["men"],
		createdAt: "2024-07-15",
		sizes: ["L", "XL"],
		colors: ["blue", "gold"],
		description:
			"An exquisite agbada made from beautiful kente fabric, perfect for special occasions.",
		quantity: 6,
	},
	{
		_id: "9",
		productName: "Women's Blouse",
		newPrice: 6000,
		oldPrice: 8000,
		media: [
			"/assets/featuredProducts/featured-product-2.jpg",
			"/assets/featuredProducts/featured-product-2.jpg",
			"/assets/featuredProducts/featured-product-2.jpg",
		],
		material: "adire",
		categories: ["women", "featured"],
		createdAt: "2024-06-18",
		sizes: ["S", "M", "L"],
		colors: ["black", "white", "red"],
		description:
			"A stylish blouse made from soft adire fabric, perfect for pairing with skirts or pants.",
		quantity: 18,
	},
	{
		_id: "10",
		productName: "Boys' Traditional Shirt",
		newPrice: 5000,
		oldPrice: 7000,
		media: [
			"/assets/products/product-1.jpg",
			"/assets/products/product-1.jpg",
			"/assets/products/product-1.jpg",
		],
		material: "ankara",
		categories: ["children"],
		createdAt: "2024-08-10",
		sizes: ["S", "M"],
		colors: ["blue", "green"],
		description:
			"A charming traditional shirt for boys made from vibrant ankara fabric.",
		quantity: 22,
	},
	{
		_id: "11",
		productName: "children's Blouse",
		newPrice: 5000,
		oldPrice: 7000,
		media: [
			"/assets/featuredProducts/featured-product-3.jpg",
			"/assets/featuredProducts/featured-product-3.jpg",
			"/assets/featuredProducts/featured-product-3.jpg",
		],
		material: "adire",
		categories: ["children", "featured"],
		createdAt: "2024-06-18",
		sizes: ["S", "M", "L"],
		colors: ["black", "white", "red"],
		description:
			"A stylish blouse made from soft adire fabric, perfect for pairing with skirts or pants.",
		quantity: 14,
	},
	{
		_id: "12",
		productName: "Women's Gown",
		newPrice: 9000,
		oldPrice: 12000,
		media: [
			"/assets/featuredProducts/featured-product-4.jpg",
			"/assets/featuredProducts/featured-product-4.jpg",
			"/assets/featuredProducts/featured-product-4.jpg",
		],
		material: "adire",
		categories: ["women", "featured"],
		createdAt: "2024-06-18",
		sizes: ["S", "M", "L"],
		colors: ["black", "white", "red"],
		description:
			"A stylish blouse made from soft adire fabric, perfect for pairing with skirts or pants.",
		quantity: 0,
	},
];
